name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Delete the old lancenet.net.zip if it exists
      - name: Delete old ZIP if it exists
        run: |
          if [ -f "lancenet.net.zip" ]; then
            echo "Deleting old lancenet.net.zip..."
            rm -f lancenet.net.zip
          else
            echo "No existing lancenet.net.zip to delete."
          fi

      # 3) Find and rename the new 'lancenet.net.*.zip' to 'lancenet.net.zip'
      - name: Rename new ZIP file
        run: |
          NEW_FILE=$(find . -type f -name "lancenet.net.*.zip" ! -name "lancenet.net.zip" | head -n 1)
          if [ -n "$NEW_FILE" ]; then
            echo "Found new ZIP: $NEW_FILE"
            mv "$NEW_FILE" lancenet.net.zip
          else
            echo "No new 'lancenet.net.*.zip' found."
          fi

      # 4) (Optional) Commit the new/renamed file if you want it in the repo
      - name: Commit new ZIP file (if changed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f "lancenet.net.zip" ]; then
            git add lancenet.net.zip
            git commit -m "Replace old ZIP with new lancenet.net.zip" || echo "No changes to commit."
            git push origin main
          else
            echo "No lancenet.net.zip to commit."
          fi

      # 5) Increment SITEVERSION (from version.txt)
      - name: Increment SITEVERSION and update version.txt
        id: siteversion
        run: |
          VERSION_FILE="version.txt"
          if [ ! -f "$VERSION_FILE" ]; then
            echo "Error: version.txt not found!" >&2
            exit 1
          fi
          CURRENT_VERSION=$(cat "$VERSION_FILE")
          echo "Current SITEVERSION: $CURRENT_VERSION"
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{printf "%d.%d.%d\n", $1, $2, $3+1}')
          echo "$NEW_VERSION" > "$VERSION_FILE"
          echo "SITEVERSION=$NEW_VERSION" >> $GITHUB_ENV

      # 6) Commit updated SITEVERSION
      - name: Commit updated version.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Increment SITEVERSION to ${{ env.SITEVERSION }}" || echo "No changes to commit."
          git push origin main

      # 7) Install unzip
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # 8) Extract the newly renamed ZIP (if it exists)
      - name: Extract the zip file
        run: |
          if [ -f "lancenet.net.zip" ]; then
            echo "Extracting lancenet.net.zip"
            unzip "lancenet.net.zip" -d ./
            ls -la
          else
            echo "No zip file found to extract."
          fi

      # 9) Replace SITEVERSION in 'index.html'
      - name: Replace SITEVERSION in 'index.html'
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: 'SITEVERSION'
          replace: '${{ env.SITEVERSION }}'
          include: 'index.html'

      # 10) Get commit count for UPLOADVERSION
      - name: Get commit count
        id: commit_count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "UPLOADVERSION=$COMMIT_COUNT" >> $GITHUB_ENV

      # 11) Replace UPLOADVERSION in 'index.html'
      - name: Replace UPLOADVERSION in 'index.html'
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: 'UPLOADVERSION'
          replace: '${{ env.UPLOADVERSION }}'
          include: 'index.html'

      - name: Display index.html
        run: cat index.html

      # 12) Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 13) Build with Jekyll
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # 14) Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      # 15) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
