name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
		  
      # 2) Remove the old ZIP from both the runner AND the repository
      - name: Remove old lancenet.net.zip
        run: |
          if [ -f "lancenet.net.zip" ]; then
            echo "Old lancenet.net.zip found locally. Removing it..."
            rm -f lancenet.net.zip

            # Remove it from the repo (if it's tracked), commit and push
            if git ls-files --error-unmatch lancenet.net.zip >/dev/null 2>&1; then
              echo "lancenet.net.zip is tracked by git. Removing from repo..."
              git rm -f lancenet.net.zip
              git commit -m "Remove old lancenet.net.zip"
              git push origin main
            else
              echo "lancenet.net.zip was not tracked in git. Nothing to commit."
            fi
          else
            echo "No existing lancenet.net.zip found locally."
          fi

      # 3) Rename the newly uploaded 'lancenet.net.*.zip' to 'lancenet.net.zip'
      #    and commit/push the renamed file to the repo
      - name: Rename and commit new ZIP file
        run: |
          # Find the new file matching 'lancenet.net.*.zip' but not 'lancenet.net.zip'
          NEW_FILE=$(find . -type f -name "lancenet.net.*.zip" ! -name "lancenet.net.zip" | head -n 1)
          if [ -n "$NEW_FILE" ]; then
            echo "Found new ZIP: $NEW_FILE"
            mv "$NEW_FILE" lancenet.net.zip

            # Now commit the new file to the repository
            git add lancenet.net.zip
            git commit -m "Add new lancenet.net.zip"
            git push origin main
          else
            echo "No new 'lancenet.net.*.zip' found."
          fi

      # 4) Increment SITEVERSION in version.txt (optional)
      - name: Increment SITEVERSION in version.txt
        id: siteversion
        run: |
          VERSION_FILE="version.txt"
          if [ ! -f "$VERSION_FILE" ]; then
            echo "Error: version.txt not found!" >&2
            exit 1
          fi
          CURRENT_VERSION=$(cat "$VERSION_FILE")
          echo "Current SITEVERSION: $CURRENT_VERSION"
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{printf "%d.%d.%d\n", $1, $2, $3+1}')
          echo "$NEW_VERSION" > "$VERSION_FILE"
          echo "SITEVERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit updated SITEVERSION
        run: |
          git add version.txt
          git commit -m "Increment SITEVERSION to ${{ env.SITEVERSION }}" || echo "No changes to commit."
          git push origin main

      # 5) Install unzip
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # 6) Extract the newly renamed lancenet.net.zip
      - name: Extract the ZIP file
        run: |
          if [ -f "lancenet.net.zip" ]; then
            echo "Extracting lancenet.net.zip"
            unzip lancenet.net.zip -d ./
            ls -la
          else
            echo "No lancenet.net.zip to extract."
          fi

      # 7) Replace SITEVERSION in 'index.html'
      - name: Replace SITEVERSION in 'index.html'
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: 'SITEVERSION'
          replace: '${{ env.SITEVERSION }}'
          include: 'index.html'

      # 8) Get commit count for UPLOADVERSION
      - name: Get commit count for UPLOADVERSION
        id: commit_count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "UPLOADVERSION=$COMMIT_COUNT" >> $GITHUB_ENV

      # 9) Replace UPLOADVERSION in 'index.html'
      - name: Replace UPLOADVERSION in 'index.html'
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: 'UPLOADVERSION'
          replace: '${{ env.UPLOADVERSION }}'
          include: 'index.html'

      - name: Display index.html
        run: cat index.html

      # 10) Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 11) Build with Jekyll
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # 12) Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      # 13) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
